### ISSUE TITLE
cannot import name force_unicode

### ISSUE THREAD

**Issue by aherok** [Soaa-/django-nested-inlines#3]
Are you sure you want to import force_unicode from django.contrib.admin.options, not from django.utils.encoding  inside admin.py? 
Only the latter place works for me. Django 1.5

**Comment by gtie** [comment]
Same here. Removing force_unicode from the import list, and doing `from django.utils.encoding import force_unicode` solved this problem for me on Django 1.5

**Comment by Soaa-** [comment]
The bug has been fixed thanks to @alexwhittemore's contribution.

**Comment by pablofm** [comment]
Still having the problem :S I've installed the software in the way you say in the readme.md

**Comment by pablofm** [comment]
Python 3.2 + django1.6
